defaults:
  - _self_

model:
  name: "Salesforce/blip-image-captioning-base"

data:
  image_dir: "data/images"
  metadata_path: "data/styles.csv"
  batch_size: 8
  num_workers: 2
  train_size: 2700
  test_size: 300

training:
  epochs: 3
  learning_rate: 5e-5
  device: "cuda"

paths:
  output_dir: "outputs"
  model_save_path: "outputs/blip_finetuned"